apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-demo-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/aniket-devop/gitops-k8s-config.git
    targetRevision: main
    path: helm/gitops-demo
    helm:
      valueFiles:
        - ../../environments/dev/values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-demo-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true